# This is a basic workflow to help you get started with Actions

name: Artifacts

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name:  "createUploadArtifact"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env: 
      ARTIFACT_NAME: Artifact1.0
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2 
      - name: create folder
        run: |
          mkdir artifacts
          ls -alt
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifacts
